package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.22

import (
	"context"
	"fmt"

	"github.com/rifkiystark/portfolios-api/cmd/project"
	"github.com/rifkiystark/portfolios-api/graph/model"
)

// CreateProject is the resolver for the createProject field.
func (r *mutationResolver) CreateProject(ctx context.Context, input project.CreateProjectRequest) (*project.ProjectResponse, error) {
	return r.ProjectService.CreateProject(ctx, input)
}

// UpdateProject is the resolver for the updateProject field.
func (r *mutationResolver) UpdateProject(ctx context.Context, id string, input project.UpdateProjectRequest) (*project.ProjectResponse, error) {
	return r.ProjectService.UpdateProject(ctx, id, input)
}

// DeleteProject is the resolver for the deleteProject field.
func (r *mutationResolver) DeleteProject(ctx context.Context, id string) (*project.ProjectResponse, error) {
	return r.ProjectService.DeleteProject(ctx, id)
}

// CreateIPR is the resolver for the createIPR field.
func (r *mutationResolver) CreateIPR(ctx context.Context, input model.CreateIPRRequest) (*model.IPRResponse, error) {
	panic(fmt.Errorf("not implemented: CreateIPR - createIPR"))
}

// UpdateIPR is the resolver for the updateIPR field.
func (r *mutationResolver) UpdateIPR(ctx context.Context, id string, input model.UpdateIPRRequest) (*model.IPRResponse, error) {
	panic(fmt.Errorf("not implemented: UpdateIPR - updateIPR"))
}

// DeleteIPR is the resolver for the deleteIPR field.
func (r *mutationResolver) DeleteIPR(ctx context.Context, id string) (*model.IPRResponse, error) {
	panic(fmt.Errorf("not implemented: DeleteIPR - deleteIPR"))
}

// Project is the resolver for the project field.
func (r *queryResolver) Project(ctx context.Context, id string) (*project.ProjectResponse, error) {
	return r.ProjectService.GetProject(ctx, id)
}

// Projects is the resolver for the projects field.
func (r *queryResolver) Projects(ctx context.Context, search *string) ([]*project.ProjectResponse, error) {
	return r.ProjectService.GetProjects(ctx, search)
}

// Ipr is the resolver for the ipr field.
func (r *queryResolver) Ipr(ctx context.Context, id string) (*model.IPRResponse, error) {
	panic(fmt.Errorf("not implemented: Ipr - ipr"))
}

// Iprs is the resolver for the iprs field.
func (r *queryResolver) Iprs(ctx context.Context, search *string) ([]*model.IPRResponse, error) {
	panic(fmt.Errorf("not implemented: Iprs - iprs"))
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
