// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type CreateIPRRequest struct {
	Title       string `json:"title"`
	PublishedAt string `json:"publishedAt"`
	Description string `json:"description"`
}

type IPRResponse struct {
	ID          string `json:"id"`
	Title       string `json:"title"`
	PublishedAt string `json:"publishedAt"`
	Description string `json:"description"`
}

type UpdateIPRRequest struct {
	Title       string `json:"title"`
	PublishedAt string `json:"publishedAt"`
	Description string `json:"description"`
}
