// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"github.com/99designs/gqlgen/graphql"
)

type CreateProject struct {
	Title          string         `json:"title"`
	Image          graphql.Upload `json:"image"`
	AdditionalInfo []string       `json:"additionalInfo"`
	Description    string         `json:"description"`
}

type Project struct {
	ID             string   `json:"id"`
	Title          string   `json:"title"`
	ImageURL       string   `json:"imageUrl"`
	AdditionalInfo []string `json:"additionalInfo"`
	Description    string   `json:"description"`
}

type UpdateProject struct {
	Title          *string         `json:"title"`
	Image          *graphql.Upload `json:"image"`
	AdditionalInfo []string        `json:"additionalInfo"`
	Description    *string         `json:"description"`
}
